// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mmhpb/miniminihub.proto

package mmhpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MiniminihubId string                 `protobuf:"bytes,1,opt,name=miniminihub_id,json=miniminihubId,proto3" json:"miniminihub_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	ClientTsMs    int64                  `protobuf:"varint,3,opt,name=client_ts_ms,json=clientTsMs,proto3" json:"client_ts_ms,omitempty"`
	Sequence      uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetMiniminihubId() string {
	if x != nil {
		return x.MiniminihubId
	}
	return ""
}

func (x *HeartbeatRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *HeartbeatRequest) GetClientTsMs() int64 {
	if x != nil {
		return x.ClientTsMs
	}
	return 0
}

func (x *HeartbeatRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerTsMs     int64                  `protobuf:"varint,2,opt,name=server_ts_ms,json=serverTsMs,proto3" json:"server_ts_ms,omitempty"`
	NextIntervalMs int32                  `protobuf:"varint,3,opt,name=next_interval_ms,json=nextIntervalMs,proto3" json:"next_interval_ms,omitempty"`
	TraceId        string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetServerTsMs() int64 {
	if x != nil {
		return x.ServerTsMs
	}
	return 0
}

func (x *HeartbeatResponse) GetNextIntervalMs() int32 {
	if x != nil {
		return x.NextIntervalMs
	}
	return 0
}

func (x *HeartbeatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MiniminihubId string                 `protobuf:"bytes,1,opt,name=miniminihub_id,json=miniminihubId,proto3" json:"miniminihub_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetMiniminihubId() string {
	if x != nil {
		return x.MiniminihubId
	}
	return ""
}

func (x *PollRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Command struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CommandId  string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	IssuedAtMs int64                  `protobuf:"varint,2,opt,name=issued_at_ms,json=issuedAtMs,proto3" json:"issued_at_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_Ping
	//	*Command_EgressOpen
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetIssuedAtMs() int64 {
	if x != nil {
		return x.IssuedAtMs
	}
	return 0
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetPing() *PingCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Command) GetEgressOpen() *EgressOpenCommand {
	if x != nil {
		if x, ok := x.Payload.(*Command_EgressOpen); ok {
			return x.EgressOpen
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_Ping struct {
	Ping *PingCommand `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type Command_EgressOpen struct {
	EgressOpen *EgressOpenCommand `protobuf:"bytes,11,opt,name=egress_open,json=egressOpen,proto3,oneof"`
}

func (*Command_Ping) isCommand_Payload() {}

func (*Command_EgressOpen) isCommand_Payload() {}

// Phase 0 : commande no-op pour prouver le canal descendant.
type PingCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          string                 `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCommand) Reset() {
	*x = PingCommand{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCommand) ProtoMessage() {}

func (x *PingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCommand.ProtoReflect.Descriptor instead.
func (*PingCommand) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{4}
}

func (x *PingCommand) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// Phase 3 : le parent demande à l'enfant d'ouvrir une sortie vers host:port.
type EgressOpenCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"` // corrèle la future EgressStream
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ViaTor        bool                   `protobuf:"varint,5,opt,name=via_tor,json=viaTor,proto3" json:"via_tor,omitempty"` // V002 P2 : sortir via TOR (SOCKS5 local) au lieu du direct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressOpenCommand) Reset() {
	*x = EgressOpenCommand{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressOpenCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressOpenCommand) ProtoMessage() {}

func (x *EgressOpenCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressOpenCommand.ProtoReflect.Descriptor instead.
func (*EgressOpenCommand) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{5}
}

func (x *EgressOpenCommand) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *EgressOpenCommand) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *EgressOpenCommand) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EgressOpenCommand) GetViaTor() bool {
	if x != nil {
		return x.ViaTor
	}
	return false
}

// Frame du flux d'égress (bidi). conn_id présent sur le 1er frame.
type EgressFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Close         bool                   `protobuf:"varint,3,opt,name=close,proto3" json:"close,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EgressFrame) Reset() {
	*x = EgressFrame{}
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EgressFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EgressFrame) ProtoMessage() {}

func (x *EgressFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mmhpb_miniminihub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EgressFrame.ProtoReflect.Descriptor instead.
func (*EgressFrame) Descriptor() ([]byte, []int) {
	return file_proto_mmhpb_miniminihub_proto_rawDescGZIP(), []int{6}
}

func (x *EgressFrame) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *EgressFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EgressFrame) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *EgressFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_mmhpb_miniminihub_proto protoreflect.FileDescriptor

const file_proto_mmhpb_miniminihub_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/mmhpb/miniminihub.proto\x12\x0eminiminihub.v1\"\x8b\x01\n" +
	"\x10HeartbeatRequest\x12%\n" +
	"\x0eminiminihub_id\x18\x01 \x01(\tR\rminiminihubId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\fclient_ts_ms\x18\x03 \x01(\x03R\n" +
	"clientTsMs\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\"\x96\x01\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12 \n" +
	"\fserver_ts_ms\x18\x02 \x01(\x03R\n" +
	"serverTsMs\x12(\n" +
	"\x10next_interval_ms\x18\x03 \x01(\x05R\x0enextIntervalMs\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"H\n" +
	"\vPollRequest\x12%\n" +
	"\x0eminiminihub_id\x18\x01 \x01(\tR\rminiminihubId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\xce\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12 \n" +
	"\fissued_at_ms\x18\x02 \x01(\x03R\n" +
	"issuedAtMs\x121\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x1b.miniminihub.v1.PingCommandH\x00R\x04ping\x12D\n" +
	"\vegress_open\x18\v \x01(\v2!.miniminihub.v1.EgressOpenCommandH\x00R\n" +
	"egressOpenB\t\n" +
	"\apayload\"!\n" +
	"\vPingCommand\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\"m\n" +
	"\x11EgressOpenCommand\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x17\n" +
	"\avia_tor\x18\x05 \x01(\bR\x06viaTor\"f\n" +
	"\vEgressFrame\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x03 \x01(\bR\x05close\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xfb\x01\n" +
	"\x12MiniMiniHubControl\x12P\n" +
	"\tHeartbeat\x12 .miniminihub.v1.HeartbeatRequest\x1a!.miniminihub.v1.HeartbeatResponse\x12E\n" +
	"\vPollCommand\x12\x1b.miniminihub.v1.PollRequest\x1a\x17.miniminihub.v1.Command0\x01\x12L\n" +
	"\fEgressStream\x12\x1b.miniminihub.v1.EgressFrame\x1a\x1b.miniminihub.v1.EgressFrame(\x010\x01B1Z/github.com/jmlmvi/miniminihub/proto/mmhpb;mmhpbb\x06proto3"

var (
	file_proto_mmhpb_miniminihub_proto_rawDescOnce sync.Once
	file_proto_mmhpb_miniminihub_proto_rawDescData []byte
)

func file_proto_mmhpb_miniminihub_proto_rawDescGZIP() []byte {
	file_proto_mmhpb_miniminihub_proto_rawDescOnce.Do(func() {
		file_proto_mmhpb_miniminihub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mmhpb_miniminihub_proto_rawDesc), len(file_proto_mmhpb_miniminihub_proto_rawDesc)))
	})
	return file_proto_mmhpb_miniminihub_proto_rawDescData
}

var file_proto_mmhpb_miniminihub_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_mmhpb_miniminihub_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),  // 0: miniminihub.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 1: miniminihub.v1.HeartbeatResponse
	(*PollRequest)(nil),       // 2: miniminihub.v1.PollRequest
	(*Command)(nil),           // 3: miniminihub.v1.Command
	(*PingCommand)(nil),       // 4: miniminihub.v1.PingCommand
	(*EgressOpenCommand)(nil), // 5: miniminihub.v1.EgressOpenCommand
	(*EgressFrame)(nil),       // 6: miniminihub.v1.EgressFrame
}
var file_proto_mmhpb_miniminihub_proto_depIdxs = []int32{
	4, // 0: miniminihub.v1.Command.ping:type_name -> miniminihub.v1.PingCommand
	5, // 1: miniminihub.v1.Command.egress_open:type_name -> miniminihub.v1.EgressOpenCommand
	0, // 2: miniminihub.v1.MiniMiniHubControl.Heartbeat:input_type -> miniminihub.v1.HeartbeatRequest
	2, // 3: miniminihub.v1.MiniMiniHubControl.PollCommand:input_type -> miniminihub.v1.PollRequest
	6, // 4: miniminihub.v1.MiniMiniHubControl.EgressStream:input_type -> miniminihub.v1.EgressFrame
	1, // 5: miniminihub.v1.MiniMiniHubControl.Heartbeat:output_type -> miniminihub.v1.HeartbeatResponse
	3, // 6: miniminihub.v1.MiniMiniHubControl.PollCommand:output_type -> miniminihub.v1.Command
	6, // 7: miniminihub.v1.MiniMiniHubControl.EgressStream:output_type -> miniminihub.v1.EgressFrame
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mmhpb_miniminihub_proto_init() }
func file_proto_mmhpb_miniminihub_proto_init() {
	if File_proto_mmhpb_miniminihub_proto != nil {
		return
	}
	file_proto_mmhpb_miniminihub_proto_msgTypes[3].OneofWrappers = []any{
		(*Command_Ping)(nil),
		(*Command_EgressOpen)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mmhpb_miniminihub_proto_rawDesc), len(file_proto_mmhpb_miniminihub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mmhpb_miniminihub_proto_goTypes,
		DependencyIndexes: file_proto_mmhpb_miniminihub_proto_depIdxs,
		MessageInfos:      file_proto_mmhpb_miniminihub_proto_msgTypes,
	}.Build()
	File_proto_mmhpb_miniminihub_proto = out.File
	file_proto_mmhpb_miniminihub_proto_goTypes = nil
	file_proto_mmhpb_miniminihub_proto_depIdxs = nil
}
