// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/mmhpb/miniminihub.proto

package mmhpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniMiniHubControl_Heartbeat_FullMethodName    = "/miniminihub.v1.MiniMiniHubControl/Heartbeat"
	MiniMiniHubControl_PollCommand_FullMethodName  = "/miniminihub.v1.MiniMiniHubControl/PollCommand"
	MiniMiniHubControl_EgressStream_FullMethodName = "/miniminihub.v1.MiniMiniHubControl/EgressStream"
)

// MiniMiniHubControlClient is the client API for MiniMiniHubControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MiniMiniHubControlClient interface {
	// L'enfant signale sa présence (état pour le graphe). Unary.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// L'enfant ouvre une server-stream ; le parent pousse les commandes au fil de l'eau.
	PollCommand(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
	// Proxy de sortie (D-17) : l'enfant ouvre ce flux bidi pour relayer une
	// connexion d'égress. 1er frame = conn_id ; ensuite bytes dans les 2 sens.
	EgressStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EgressFrame, EgressFrame], error)
}

type miniMiniHubControlClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniMiniHubControlClient(cc grpc.ClientConnInterface) MiniMiniHubControlClient {
	return &miniMiniHubControlClient{cc}
}

func (c *miniMiniHubControlClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MiniMiniHubControl_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniMiniHubControlClient) PollCommand(ctx context.Context, in *PollRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MiniMiniHubControl_ServiceDesc.Streams[0], MiniMiniHubControl_PollCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PollRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniMiniHubControl_PollCommandClient = grpc.ServerStreamingClient[Command]

func (c *miniMiniHubControlClient) EgressStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EgressFrame, EgressFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MiniMiniHubControl_ServiceDesc.Streams[1], MiniMiniHubControl_EgressStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EgressFrame, EgressFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniMiniHubControl_EgressStreamClient = grpc.BidiStreamingClient[EgressFrame, EgressFrame]

// MiniMiniHubControlServer is the server API for MiniMiniHubControl service.
// All implementations must embed UnimplementedMiniMiniHubControlServer
// for forward compatibility.
type MiniMiniHubControlServer interface {
	// L'enfant signale sa présence (état pour le graphe). Unary.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// L'enfant ouvre une server-stream ; le parent pousse les commandes au fil de l'eau.
	PollCommand(*PollRequest, grpc.ServerStreamingServer[Command]) error
	// Proxy de sortie (D-17) : l'enfant ouvre ce flux bidi pour relayer une
	// connexion d'égress. 1er frame = conn_id ; ensuite bytes dans les 2 sens.
	EgressStream(grpc.BidiStreamingServer[EgressFrame, EgressFrame]) error
	mustEmbedUnimplementedMiniMiniHubControlServer()
}

// UnimplementedMiniMiniHubControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniMiniHubControlServer struct{}

func (UnimplementedMiniMiniHubControlServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMiniMiniHubControlServer) PollCommand(*PollRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method PollCommand not implemented")
}
func (UnimplementedMiniMiniHubControlServer) EgressStream(grpc.BidiStreamingServer[EgressFrame, EgressFrame]) error {
	return status.Error(codes.Unimplemented, "method EgressStream not implemented")
}
func (UnimplementedMiniMiniHubControlServer) mustEmbedUnimplementedMiniMiniHubControlServer() {}
func (UnimplementedMiniMiniHubControlServer) testEmbeddedByValue()                            {}

// UnsafeMiniMiniHubControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniMiniHubControlServer will
// result in compilation errors.
type UnsafeMiniMiniHubControlServer interface {
	mustEmbedUnimplementedMiniMiniHubControlServer()
}

func RegisterMiniMiniHubControlServer(s grpc.ServiceRegistrar, srv MiniMiniHubControlServer) {
	// If the following call panics, it indicates UnimplementedMiniMiniHubControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniMiniHubControl_ServiceDesc, srv)
}

func _MiniMiniHubControl_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniMiniHubControlServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniMiniHubControl_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniMiniHubControlServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniMiniHubControl_PollCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MiniMiniHubControlServer).PollCommand(m, &grpc.GenericServerStream[PollRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniMiniHubControl_PollCommandServer = grpc.ServerStreamingServer[Command]

func _MiniMiniHubControl_EgressStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MiniMiniHubControlServer).EgressStream(&grpc.GenericServerStream[EgressFrame, EgressFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MiniMiniHubControl_EgressStreamServer = grpc.BidiStreamingServer[EgressFrame, EgressFrame]

// MiniMiniHubControl_ServiceDesc is the grpc.ServiceDesc for MiniMiniHubControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniMiniHubControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miniminihub.v1.MiniMiniHubControl",
	HandlerType: (*MiniMiniHubControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _MiniMiniHubControl_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollCommand",
			Handler:       _MiniMiniHubControl_PollCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EgressStream",
			Handler:       _MiniMiniHubControl_EgressStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mmhpb/miniminihub.proto",
}
